apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-ingress
spec:
  rules:
  - host: yas.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yas-storefront-service
            port:
              number: 80
      - path: /api # Mọi yêu cầu gọi data sẽ vào đây
        pathType: Prefix
        backend:
          service:
            name: yas-api-gateway-service # Đảm bảo tên này khớp với service gateway
            port:
              number: 8080
  - host: admin.yas.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yas-back-office-service
            port:
              number: 80