apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE yas_product;
    CREATE DATABASE yas_customer;
    CREATE DATABASE yas_cart;
    CREATE DATABASE yas_inventory;
    CREATE DATABASE yas_order;
    CREATE DATABASE yas_media;
    CREATE DATABASE yas_location;
    CREATE DATABASE yas_payment;
    CREATE DATABASE yas_payment_paypal;
    CREATE DATABASE yas_promotion;
    CREATE DATABASE yas_rating;
    CREATE DATABASE yas_search;
    CREATE DATABASE yas_tax;
    CREATE DATABASE keycloak_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        # Chúng ta dùng database mặc định là postgres để chạy script init
        - name: POSTGRES_DB
          value: postgres 
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432