# --- STOREFRONT UI ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-storefront-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yas-storefront-ui
  template:
    metadata:
      labels:
        app: yas-storefront-ui
    spec:
      containers:
      - name: ui
        image: longle2112/yas-storefront-ui:latest
        ports:
        - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_URL
            value: "http://yas.local/api"
---
apiVersion: v1
kind: Service
metadata:
  name: yas-storefront-ui-service
spec:
  selector:
    app: yas-storefront-ui
  ports:
    - port: 80
      targetPort: 3000
---
# --- STOREFRONT BFF ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-storefront-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yas-storefront-bff
  template:
    metadata:
      labels:
        app: yas-storefront-bff
    spec:
      containers:
      - name: bff
        image: longle2112/yas-storefront-bff:latest
        ports:
        - containerPort: 8080
        env:
          - name: PRODUCT_SERVICE_URL
            value: "http://yas-product-service:8080"
          - name: ORDER_SERVICE_URL
            value: "http://yas-order-service:8080"
          - name: CART_SERVICE_URL
            value: "http://yas-cart-service:8080"
          - name: CUSTOMER_SERVICE_URL
            value: "http://yas-customer-service:8080"
          - name: PAYMENT_SERVICE_URL
            value: "http://yas-payment-service:8080"
          - name: INVENTORY_SERVICE_URL
            value: "http://yas-inventory-service:8080"
          - name: LOCATION_SERVICE_URL
            value: "http://yas-location-service:8080"
          - name: MEDIA_SERVICE_URL
            value: "http://yas-media-service:8080"
          - name: PROMOTION_SERVICE_URL
            value: "http://yas-promotion-service:8080"
          - name: RATING_SERVICE_URL
            value: "http://yas-rating-service:8080"
          - name: SEARCH_SERVICE_URL
            value: "http://yas-search-service:8080"
          - name: TAX_SERVICE_URL
            value: "http://yas-tax-service:8080"
          - name: PAYMENT_PAYPAL_URL
            value: "http://yas-payment-paypal-service:8080"
          - name: KEYCLOAK_URL
            value: "http://keycloak-service:8080"
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
            value: "http://keycloak-service:8080/realms/Yas"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            value: "http://keycloak-service:8080/realms/Yas"
---
apiVersion: v1
kind: Service
metadata:
  name: yas-storefront-bff-service
spec:
  selector:
    app: yas-storefront-bff
  ports:
    - port: 8080
      targetPort: 8080

# --- BACK-OFFICE UI ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-back-office-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yas-back-office-ui
  template:
    metadata:
      labels:
        app: yas-back-office-ui
    spec:
      containers:
      - name: ui
        image: longle2112/yas-back-office-ui:latest
        ports:
        - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_URL
            value: "http://admin.yas.local/api"
---
apiVersion: v1
kind: Service
metadata:
  name: yas-back-office-ui-service
spec:
  selector:
    app: yas-back-office-ui
  ports:
    - port: 80
      targetPort: 3000
---
# --- BACK-OFFICE BFF ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-back-office-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yas-back-office-bff
  template:
    metadata:
      labels:
        app: yas-back-office-bff
    spec:
      containers:
      - name: bff
        image: longle2112/yas-backoffice-bff:latest
        ports:
        - containerPort: 8080
        env:
          - name: PRODUCT_SERVICE_URL
            value: "http://yas-product-service:8080"
          - name: ORDER_SERVICE_URL
            value: "http://yas-order-service:8080"
          - name: CART_SERVICE_URL
            value: "http://yas-cart-service:8080"
          - name: CUSTOMER_SERVICE_URL
            value: "http://yas-customer-service:8080"
          - name: PAYMENT_SERVICE_URL
            value: "http://yas-payment-service:8080"
          - name: INVENTORY_SERVICE_URL
            value: "http://yas-inventory-service:8080"
          - name: LOCATION_SERVICE_URL
            value: "http://yas-location-service:8080"
          - name: MEDIA_SERVICE_URL
            value: "http://yas-media-service:8080"
          - name: PROMOTION_SERVICE_URL
            value: "http://yas-promotion-service:8080"
          - name: RATING_SERVICE_URL
            value: "http://yas-rating-service:8080"
          - name: SEARCH_SERVICE_URL
            value: "http://yas-search-service:8080"
          - name: TAX_SERVICE_URL
            value: "http://yas-tax-service:8080"
          - name: PAYMENT_PAYPAL_URL
            value: "http://yas-payment-paypal-service:8080"
          - name: KEYCLOAK_URL
            value: "http://keycloak-service:8080"
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
            value: "http://keycloak-service:8080/realms/Yas"
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
            value: "http://keycloak-service:8080/realms/Yas"
---
apiVersion: v1
kind: Service
metadata:
  name: yas-back-office-bff-service
spec:
  selector:
    app: yas-back-office-bff
  ports:
    - port: 8080
      targetPort: 8080