name: YAS Microservices CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # JOB 1: Kiểm tra xem service nào thay đổi
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }} # Trả về danh sách ví dụ: ["cart", "tax"]
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            tax: 'tax/**'
            search: 'search/**'
            rating: 'rating/**'
            promotion: 'promotion/**'
            payment-paypal: 'payment-paypal/**'
            payment: 'payment/**'
            order: 'order/**'
            media: 'media/**'
            location: 'location/**'
            inventory: 'inventory/**'
            customer: 'customer/**'
            cart: 'cart/**'
            product: 'product/**'

  # JOB 2: Chỉ build những service có trong danh sách thay đổi
  build-and-push:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' && needs.detect-changes.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }} # Matrix tự động tạo job cho mỗi service thay đổi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Environment (Java & Cache)
        uses: ./.github/workflows/actions

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Short Commit ID
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn clean install -pl ${{ matrix.service }} -am -DskipTests

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yas-${{ matrix.service }}:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yas-${{ matrix.service }}:latest